In [24]:
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('Train.csv')
test=pd.read_csv('Test.csv')
data.head()

,ID,DATOP,FLTID,DEPSTN,ARRSTN,STD,STA,STATUS,AC,target
0,train_id_0,2016-01-03,TU 0712,CMN,TUN,2016-01-03 10:30:00,2016-01-03 12.55.00,ATA,TU 32AIMN,260.0
1,train_id_1,2016-01-13,TU 0757,MXP,TUN,2016-01-13 15:05:00,2016-01-13 16.55.00,ATA,TU 31BIMO,20.0
2,train_id_2,2016-01-16,TU 0214,TUN,IST,2016-01-16 04:10:00,2016-01-16 06.45.00,ATA,TU 32AIMN,0.0
3,train_id_3,2016-01-17,TU 0480,DJE,NTE,2016-01-17 14:10:00,2016-01-17 17.00.00,ATA,TU 736IOK,0.0
4,train_id_4,2016-01-17,TU 0338,TUN,ALG,2016-01-17 14:30:00,2016-01-17 15.50.00,ATA,TU 320IMU,22.0

In [25]:
test.head()
data.isnull().sum()

ID        0
DATOP     0
FLTID     0
DEPSTN    0
ARRSTN    0
STD       0
STA       0
STATUS    0
AC        0
target    0
dtype: int64

In [22]:
X=pd.concat([data,test],axis=1)

In [23]:
X = data.drop(['ID'], axis = 1)

In [20]:
X.head()

,DATOP,FLTID,DEPSTN,ARRSTN,STD,STA,STATUS,AC,target
0,2016-01-03,TU 0712,CMN,TUN,2016-01-03 10:30:00,2016-01-03 12.55.00,ATA,TU 32AIMN,260.0
1,2016-01-13,TU 0757,MXP,TUN,2016-01-13 15:05:00,2016-01-13 16.55.00,ATA,TU 31BIMO,20.0
2,2016-01-16,TU 0214,TUN,IST,2016-01-16 04:10:00,2016-01-16 06.45.00,ATA,TU 32AIMN,0.0
3,2016-01-17,TU 0480,DJE,NTE,2016-01-17 14:10:00,2016-01-17 17.00.00,ATA,TU 736IOK,0.0
4,2016-01-17,TU 0338,TUN,ALG,2016-01-17 14:30:00,2016-01-17 15.50.00,ATA,TU 320IMU,22.0

In [5]:
dat_op_list=X['DATOP']
timespam=pd.to_datetime(dat_op_list)
year=timespam.dt.year
month=timespam.dt.month
day=timespam.dt.day
yeardatop=pd.DataFrame(year)
monthdatop=pd.DataFrame(month)
daydatop=pd.DataFrame(day)
std_list=X['STD']
timespam=pd.to_datetime(std_list)
year=timespam.dt.year
month=timespam.dt.month
day=timespam.dt.day
hour=timespam.dt.hour
minutes=timespam.dt.minute
sec=timespam.dt.second
yearstd=pd.DataFrame(year)
monthstd=pd.DataFrame(month)
hourstd=pd.DataFrame(hour)
minstd=pd.DataFrame(minutes)
secstd=pd.DataFrame(sec)
daystd=pd.DataFrame(day)
sta_list=X['STA']
timespam=pd.to_datetime(std_list)
year=timespam.dt.year
month=timespam.dt.month
day=timespam.dt.day
hour=timespam.dt.hour
minutes=timespam.dt.minute
sec=timespam.dt.second
yearsta=pd.DataFrame(year)
monthsta=pd.DataFrame(month)
hoursta=pd.DataFrame(hour)
minsta=pd.DataFrame(minutes)
secsta=pd.DataFrame(sec)
daysta=pd.DataFrame(day)

In [6]:
var=pd.concat([yeardatop,monthdatop,daydatop,yearstd,monthstd,hourstd,minstd,secstd,daystd,yearsta,monthsta,hoursta,minsta,secsta,daysta],axis='columns')

In [7]:
var.columns=['yeardatop','monthdatop','daydatop','yearstd','monthstd','hourstd','minstd','secstd','daystd','yearsta','monthsta','hoursta','minsta','secsta','daysta']

In [21]:
var

,yeardatop,monthdatop,daydatop,yearstd,monthstd,hourstd,minstd,secstd,daystd,yearsta,monthsta,hoursta,minsta,secsta,daysta
0,2016,1,3,2016,1,10,30,0,3,2016,1,10,30,0,3
1,2016,1,13,2016,1,15,5,0,13,2016,1,15,5,0,13
2,2016,1,16,2016,1,4,10,0,16,2016,1,4,10,0,16
3,2016,1,17,2016,1,14,10,0,17,2016,1,14,10,0,17
4,2016,1,17,2016,1,14,30,0,17,2016,1,14,30,0,17
5,2016,1,17,2016,1,16,20,0,17,2016,1,16,20,0,17
6,2016,1,18,2016,1,7,15,0,18,2016,1,7,15,0,18
7,2016,1,18,2016,1,7,35,0,18,2016,1,7,35,0,18
8,2016,1,18,2016,1,7,40,0,18,2016,1,7,40,0,18
9,2016,1,18,2016,1,7,45,0,18,2016,1,7,45,0,18
10,2016,1,18,2016,1,7,55,0,18,2016,1,7,55,0,18
11,2016,1,20,2016,1,18,30,0,20,2016,1,18,30,0,20
12,2016,1,20,2016,1,19,40,0,20,2016,1,19,40,0,20
13,2016,1,21,2016,1,20,10,0,21,2016,1,20,10,0,21
14,2016,1,22,2016,1,7,5,0,22,2016,1,7,5,0,22
15,2016,1,22,2016,1,17,45,0,22,2016,1,17,45,0,22
16,2016,1,22,2016,1,18,30,0,22,2016,1,18,30,0,22
17,2016,1,23,2016,1,5,30,0,23,2016,1,5,30,0,23
18,2016,1,22,2016,1,19,40,0,22,2016,1,19,40,0,22
19,2016,1,23,2016,1,8,50,0,23,2016,1,8,50,0,23
20,2016,1,23,2016,1,10,55,0,23,2016,1,10,55,0,23
21,2016,1,24,2016,1,14,5,0,24,2016,1,14,5,0,24
22,2016,1,27,2016,1,11,35,0,27,2016,1,11,35,0,27
23,2016,2,1,2016,2,19,40,0,1,2016,2,19,40,0,1
24,2016,2,2,2016,2,6,55,0,2,2016,2,6,55,0,2
25,2016,2,2,2016,2,8,0,0,2,2016,2,8,0,0,2
26,2016,2,2,2016,2,18,30,0,2,2016,2,18,30,0,2
27,2016,2,2,2016,2,18,30,0,2,2016,2,18,30,0,2
28,2016,2,2,2016,2,20,10,0,2,2016,2,20,10,0,2
29,2016,2,3,2016,2,1,55,0,3,2016,2,1,55,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107803,2018,1,28,2018,1,20,0,0,28,2018,1,20,0,0,28
107804,2018,4,1,2018,4,17,45,0,1,2018,4,17,45,0,1
107805,2018,4,10,2018,4,6,0,0,10,2018,4,6,0,0,10
107806,2018,1,5,2018,1,8,0,0,5,2018,1,8,0,0,5
107807,2018,1,24,2018,1,13,45,0,24,2018,1,13,45,0,24
107808,2018,4,13,2018,4,22,0,0,13,2018,4,22,0,0,13
107809,2018,8,5,2018,8,12,30,0,5,2018,8,12,30,0,5
107810,2018,6,30,2018,6,14,30,0,30,2018,6,14,30,0,30
107811,2018,8,21,2018,8,19,45,0,21,2018,8,19,45,0,21
107812,2018,10,21,2018,10,11,30,0,21,2018,10,11,30,0,21
107813,2018,8,11,2018,8,1,0,0,11,2018,8,1,0,0,11
107814,2018,2,1,2018,2,7,0,0,1,2018,2,7,0,0,1
107815,2018,12,2,2018,12,22,0,0,2,2018,12,22,0,0,2
107816,2018,1,15,2018,1,22,0,0,15,2018,1,22,0,0,15
107817,2018,8,3,2018,8,16,15,0,3,2018,8,16,15,0,3
107818,2018,12,31,2018,12,22,0,0,31,2018,12,22,0,0,31
107819,2018,2,14,2018,2,5,0,0,14,2018,2,5,0,0,14
107820,2018,12,24,2018,12,9,45,0,24,2018,12,9,45,0,24
107821,2018,1,24,2018,1,15,0,0,24,2018,1,15,0,0,24
107822,2018,8,2,2018,8,16,15,0,2,2018,8,16,15,0,2
107823,2018,4,12,2018,4,17,5,0,12,2018,4,17,5,0,12
107824,2018,2,9,2018,2,10,0,0,9,2018,2,10,0,0,9
107825,2018,8,8,2018,8,22,0,0,8,2018,8,22,0,0,8
107826,2018,10,15,2018,10,19,45,0,15,2018,10,19,45,0,15
107827,2018,12,19,2018,12,23,45,0,19,2018,12,23,45,0,19
107828,2018,7,5,2018,7,23,0,0,5,2018,7,23,0,0,5
107829,2018,1,13,2018,1,8,0,0,13,2018,1,8,0,0,13
107830,2018,11,7,2018,11,5,0,0,7,2018,11,5,0,0,7
107831,2018,1,23,2018,1,18,0,0,23,2018,1,18,0,0,23
107832,2018,11,13,2018,11,6,15,0,13,2018,11,6,15,0,13

In [9]:
X=pd.concat([X,var],axis=1)

In [10]:
X.head()

,DATOP,FLTID,DEPSTN,ARRSTN,STD,STA,STATUS,AC,target,yeardatop,...,hourstd,minstd,secstd,daystd,yearsta,monthsta,hoursta,minsta,secsta,daysta
0,2016-01-03,TU 0712,CMN,TUN,2016-01-03 10:30:00,2016-01-03 12.55.00,ATA,TU 32AIMN,260.0,2016,...,10,30,0,3,2016,1,10,30,0,3
1,2016-01-13,TU 0757,MXP,TUN,2016-01-13 15:05:00,2016-01-13 16.55.00,ATA,TU 31BIMO,20.0,2016,...,15,5,0,13,2016,1,15,5,0,13
2,2016-01-16,TU 0214,TUN,IST,2016-01-16 04:10:00,2016-01-16 06.45.00,ATA,TU 32AIMN,0.0,2016,...,4,10,0,16,2016,1,4,10,0,16
3,2016-01-17,TU 0480,DJE,NTE,2016-01-17 14:10:00,2016-01-17 17.00.00,ATA,TU 736IOK,0.0,2016,...,14,10,0,17,2016,1,14,10,0,17
4,2016-01-17,TU 0338,TUN,ALG,2016-01-17 14:30:00,2016-01-17 15.50.00,ATA,TU 320IMU,22.0,2016,...,14,30,0,17,2016,1,14,30,0,17

In [11]:
X = X.drop(['DATOP','STD','STA'], axis = 1)

In [12]:
X

,FLTID,DEPSTN,ARRSTN,STATUS,AC,target,yeardatop,monthdatop,daydatop,yearstd,...,hourstd,minstd,secstd,daystd,yearsta,monthsta,hoursta,minsta,secsta,daysta
0,TU 0712,CMN,TUN,ATA,TU 32AIMN,260.0,2016,1,3,2016,...,10,30,0,3,2016,1,10,30,0,3
1,TU 0757,MXP,TUN,ATA,TU 31BIMO,20.0,2016,1,13,2016,...,15,5,0,13,2016,1,15,5,0,13
2,TU 0214,TUN,IST,ATA,TU 32AIMN,0.0,2016,1,16,2016,...,4,10,0,16,2016,1,4,10,0,16
3,TU 0480,DJE,NTE,ATA,TU 736IOK,0.0,2016,1,17,2016,...,14,10,0,17,2016,1,14,10,0,17
4,TU 0338,TUN,ALG,ATA,TU 320IMU,22.0,2016,1,17,2016,...,14,30,0,17,2016,1,14,30,0,17
5,TU 0283,TLS,TUN,ATA,TU 736IOP,53.0,2016,1,17,2016,...,16,20,0,17,2016,1,16,20,0,17
6,TU 0514,TUN,BCN,ATA,TU 32AIMH,10.0,2016,1,18,2016,...,7,15,0,18,2016,1,7,15,0,18
7,TU 0716,TUN,ORY,ATA,TU 32AIMI,15.0,2016,1,18,2016,...,7,35,0,18,2016,1,7,35,0,18
8,TU 0752,TUN,FCO,ATA,TU 32AIMC,16.0,2016,1,18,2016,...,7,40,0,18,2016,1,7,40,0,18
9,TU 0996,TUN,NCE,ATA,TU 31AIMK,21.0,2016,1,18,2016,...,7,45,0,18,2016,1,7,45,0,18
10,TU 0930,TUN,MRS,ATA,TU 32AIMF,12.0,2016,1,18,2016,...,7,55,0,18,2016,1,7,55,0,18
11,TU 0724,TUN,ORY,ATA,TU 32AIMP,18.0,2016,1,20,2016,...,18,30,0,20,2016,1,18,30,0,20
12,TU 0913,TUN,MED,ATA,TU 320IMR,0.0,2016,1,20,2016,...,19,40,0,20,2016,1,19,40,0,20
13,TU 0217,IST,TUN,ATA,TU 320IMU,0.0,2016,1,21,2016,...,20,10,0,21,2016,1,20,10,0,21
14,TU 0744,TUN,FRA,ATA,TU 736IOP,18.0,2016,1,22,2016,...,7,5,0,22,2016,1,7,5,0,22
15,TU 0706,CMN,TUN,ATA,TU 320IMR,0.0,2016,1,22,2016,...,17,45,0,22,2016,1,17,45,0,22
16,TU 0723,ORY,TUN,ATA,TU 332IFN,37.0,2016,1,22,2016,...,18,30,0,22,2016,1,18,30,0,22
17,TU 0726,MIR,BRU,ATA,TU 31AIMJ,149.0,2016,1,23,2016,...,5,30,0,23,2016,1,5,30,0,23
18,TU 0913,TUN,MED,ATA,TU 320IMT,30.0,2016,1,22,2016,...,19,40,0,22,2016,1,19,40,0,22
19,TU 9038,TUN,DJE,ATA,TU 736IOL,19.0,2016,1,23,2016,...,8,50,0,23,2016,1,8,50,0,23
20,TU 0717,ORY,TUN,ATA,TU 32AIMI,27.0,2016,1,23,2016,...,10,55,0,23,2016,1,10,55,0,23
21,TU 0430,DJE,LYS,ATA,TU 31AIMJ,0.0,2016,1,24,2016,...,14,5,0,24,2016,1,14,5,0,24
22,TU 0789,BRU,TUN,ATA,TU 32AIMF,31.0,2016,1,27,2016,...,11,35,0,27,2016,1,11,35,0,27
23,TU 0913,TUN,MED,ATA,TU 320IMT,10.0,2016,2,1,2016,...,19,40,0,1,2016,2,19,40,0,1
24,TU 0711,TUN,CMN,ATA,TU 320IMU,24.0,2016,2,2,2016,...,6,55,0,2,2016,2,6,55,0,2
25,TU 0226,TUN,BEG,ATA,TU 32AIMN,9.0,2016,2,2,2016,...,8,0,0,2,2016,2,8,0,0,2
26,TU 0723,ORY,TUN,ATA,TU 320IMR,0.0,2016,2,2,2016,...,18,30,0,2,2016,2,18,30,0,2
27,TU 0397,TUN,OUA,ATA,TU 31BIMQ,0.0,2016,2,2,2016,...,18,30,0,2,2016,2,18,30,0,2
28,TU 0217,IST,TUN,ATA,TU 32AIMN,0.0,2016,2,2,2016,...,20,10,0,2,2016,2,20,10,0,2
29,TU 0398,ABJ,TUN,ATA,TU 31BIMQ,0.0,2016,2,3,2016,...,1,55,0,3,2016,2,1,55,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107803,AOG 0000,TUN,TUN,SCH,TU 320IMT,0.0,2018,1,28,2018,...,20,0,0,28,2018,1,20,0,0,28
107804,UG 0030,TUN,TOE,SCH,TU CR9ISA,0.0,2018,4,1,2018,...,17,45,0,1,2018,4,17,45,0,1
107805,UG 0002,TUN,DJE,SCH,TU CR9ISA,0.0,2018,4,10,2018,...,6,0,0,10,2018,4,6,0,0,10
107806,UG 0003,DJE,TUN,SCH,TU CR9ISA,0.0,2018,1,5,2018,...,8,0,0,5,2018,1,8,0,0,5
107807,UG 0008,TUN,DJE,SCH,UG AT7LBD,0.0,2018,1,24,2018,...,13,45,0,24,2018,1,13,45,0,24
107808,WKL 0000,TUN,TUN,SCH,TU 31BIMO,0.0,2018,4,13,2018,...,22,0,0,13,2018,4,22,0,0,13
107809,UG 0403,DJE,TUN,SCH,TU CR9ISA,0.0,2018,8,5,2018,...,12,30,0,5,2018,8,12,30,0,5
107810,UG 0008,TUN,DJE,SCH,TU CR9ISA,0.0,2018,6,30,2018,...,14,30,0,30,2018,6,14,30,0,30
107811,UG 0011,DJE,TUN,SCH,UG AT7LBD,0.0,2018,8,21,2018,...,19,45,0,21,2018,8,19,45,0,21
107812,UG 1301,MLA,TUN,SCH,UG AT7LBE,0.0,2018,10,21,2018,...,11,30,0,21,2018,10,11,30,0,21
107813,WKL 0000,MIR,MIR,SCH,TU 736ION,0.0,2018,8,11,2018,...,1,0,0,11,2018,8,1,0,0,11
107814,A 0000,TUN,TUN,SCH,TU 320IMS,0.0,2018,2,1,2018,...,7,0,0,1,2018,2,7,0,0,1
107815,WKL 0000,TUN,TUN,SCH,TU 32AIML,0.0,2018,12,2,2018,...,22,0,0,2,2018,12,22,0,0,2
107816,AOG 0000,TUN,TUN,SCH,TU 320IMR,0.0,2018,1,15,2018,...,22,0,0,15,2018,1,22,0,0,15
107817,UG 0009,DJE,TUN,SCH,UG AT7LBD,0.0,2018,8,3,2018,...,16,15,0,3,2018,8,16,15,0,3
107818,WKL 0000,TUN,TUN,SCH,TU 32AIMF,0.0,2018,12,31,2018,...,22,0,0,31,2018,12,22,0,0,31
107819,UG 0041,TOE,TUN,SCH,TU CR9ISA,0.0,2018,2,14,2018,...,5,0,0,14,2018,2,5,0,0,14
107820,UG 1759,PMO,TUN,SCH,UG AT7LBD,0.0,2018,12,24,2018,...,9,45,0,24,2018,12,9,45,0,24
107821,WKL 0000,TUN,TUN,SCH,TU 320IMU,0.0,2018,1,24,2018,...,15,0,0,24,2018,1,15,0,0,24
107822,UG 0009,DJE,TUN,SCH,UG AT7LBE,0.0,2018,8,2,2018,...,16,15,0,2,2018,8,16,15,0,2
107823,TU 9001,MIR,TUN,ATA,TU 736IOL,0.0,2018,4,12,2018,...,17,5,0,12,2018,4,17,5,0,12
107824,UG 1730,TUN,NAP,SCH,TU CR9ISA,0.0,2018,2,9,2018,...,10,0,0,9,2018,2,10,0,0,9
107825,WKL 0000,TUN,TUN,SCH,TU 320IMV,0.0,2018,8,8,2018,...,22,0,0,8,2018,8,22,0,0,8
107826,UG 0011,DJE,TUN,SCH,UG AT7LBE,0.0,2018,10,15,2018,...,19,45,0,15,2018,10,19,45,0,15
107827,SGT 0000,TUN,TUN,SCH,TU 736IOP,0.0,2018,12,19,2018,...,23,45,0,19,2018,12,23,45,0,19
107828,WKL 0000,TUN,TUN,SCH,TU 32AIML,0.0,2018,7,5,2018,...,23,0,0,5,2018,7,23,0,0,5
107829,UG 0003,DJE,TUN,SCH,UG AT7AT7,0.0,2018,1,13,2018,...,8,0,0,13,2018,1,8,0,0,13
107830,SGT 0000,TUN,TUN,SCH,TU 736IOK,0.0,2018,11,7,2018,...,5,0,0,7,2018,11,5,0,0,7
107831,UG 0010,TUN,DJE,ATA,TU CR9ISA,0.0,2018,1,23,2018,...,18,0,0,23,2018,1,18,0,0,23
107832,UG 0002,TUN,DJE,SCH,TU CR9ISA,0.0,2018,11,13,2018,...,6,15,0,13,2018,11,6,15,0,13

In [15]:
X = pd.get_dummies(X, drop_first=False)

In [26]:
Y= X['target'].values

In [27]:
Y

array([260.,  20.,   0., ...,   0.,   0.,   0.])

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3)